### ISSUE TITLE
Remove home wording and make logo homelink

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/pan-cnc#11]
Looking at the Palo Alto look and feel of other apps, there is no home link.  The Logo and AppName are either just images or, if there is any action on it, it is a drop down with links to other apps (which we aren't going to do).  We should look at removing the term "Home" and just making the logo the home link to stay within corporate UX.  
This is related to #12 as part of the documentation of how to get the look and feel.

**Comment by nembery** [comment]
fixed via commit: 92e1f46
