### ISSUE TITLE
FW_NAME writes to init-cfg device-group and template name fields

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/pan-cnc#4]
The device name in the simple demo model is used to create the device-group and stack using the FW_NAME value. Need to confirm and/or correct the issue where the instantiated FW doesn't link to its respective DG and stack.

Currently the device will connect to Panorama and show connected. It will also get the proper hostname. However in Panorama, the serial-number not auto associated to the DG and stack. Assumption that the init-cfg file not populated with these values.

**Comment by nembery** [comment]
This was corrected some time ago
