### ISSUE TITLE
Add formatted boolean checkbox option

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/pan-cnc#7]
The current checkbox type is based on a list that shows all values, even if to be boolean.

Ideally want to have a single checkbox as a BooleanField with the description to the right of the box. This creates a more intuitive boolean option in the menu.

NOTE: Also with checkbox you have to set required=False to allow for unchecked boxes.

**Comment by nembery** [comment]
@punisherVX added this already
